query Projects {
  projects {
    data {
      id
      attributes {
        name
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}